/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

/**
 *
 * @author seydou
 */
public class Gestion_etudiants extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_etudiants
     */
    public Gestion_etudiants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_ine = new javax.swing.JTextField();
        txt_id3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_moyenne = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbx_ufr = new javax.swing.JComboBox<>();
        btn_retour = new javax.swing.JButton();
        btn_modier = new javax.swing.JButton();
        btn_supprimer1 = new javax.swing.JButton();
        btn_ajouter2 = new javax.swing.JButton();
        btn_actualiser1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_etudiants = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.cyan);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel2.setText("GESTION DES ETUDIANTS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 450, 70));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 30));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 30));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel5.setText("Ufr :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 30));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel6.setText("Prenom :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 30));

        txt_prenom.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        getContentPane().add(txt_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 210, -1));

        txt_nom.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 210, -1));

        txt_ine.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        getContentPane().add(txt_ine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, -1));

        txt_id3.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        getContentPane().add(txt_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel7.setText("Ine :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 30));

        txt_moyenne.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        getContentPane().add(txt_moyenne, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 210, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel8.setText("Moyenne :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 30));

        cbx_ufr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SET" }));
        cbx_ufr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ufrActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_ufr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 210, -1));

        btn_retour.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        btn_retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outils/icons8-undo-30.png"))); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });
        getContentPane().add(btn_retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 150, 40));

        btn_modier.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        btn_modier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outils/icons8-pencil-30.png"))); // NOI18N
        btn_modier.setText("Modifer");
        btn_modier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modierActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modier, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 150, 40));

        btn_supprimer1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        btn_supprimer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outils/icons8-remove-30.png"))); // NOI18N
        btn_supprimer1.setText("Supprimer");
        btn_supprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_supprimer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 150, 40));

        btn_ajouter2.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        btn_ajouter2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outils/icons8-plus-30.png"))); // NOI18N
        btn_ajouter2.setText("Ajouter");
        btn_ajouter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ajouter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, 40));

        btn_actualiser1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        btn_actualiser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outils/icons8-synchronize-30.png"))); // NOI18N
        btn_actualiser1.setText("Actualiser");
        btn_actualiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiser1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualiser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 150, 40));

        table_etudiants.setBackground(java.awt.Color.cyan);
        table_etudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Prenom", "Nom", "Ine", "Moyenne", "Ufr"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_etudiants.setGridColor(java.awt.Color.blue);
        jScrollPane1.setViewportView(table_etudiants);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 98, 630, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outils/wallpaper7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_ufrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ufrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ufrActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_modierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modierActionPerformed

    private void btn_ajouter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ajouter2ActionPerformed

    private void btn_supprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supprimer1ActionPerformed

    private void btn_actualiser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actualiser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_etudiants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualiser1;
    private javax.swing.JButton btn_ajouter2;
    private javax.swing.JButton btn_modier;
    private javax.swing.JButton btn_retour;
    private javax.swing.JButton btn_supprimer1;
    private javax.swing.JComboBox<String> cbx_ufr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_etudiants;
    private javax.swing.JTextField txt_id3;
    private javax.swing.JTextField txt_ine;
    private javax.swing.JTextField txt_moyenne;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    // End of variables declaration//GEN-END:variables
}
